development: &default
  adapter: postgresql
  encoding: unicode
  database: inst_lti_development
  host: localhost
  pool: 5
  username: postgres
  password:

test:
  <<: *default
  database: inst_lti_test
