default: &default
  inst_lti_twitter_consumer_key:        INST_LTI_TWITTER_CONSUMER_KEY
  inst_lti_twitter_consumer_secret:     INST_LTI_TWITTER_CONSUMER_SECRET
  inst_lti_twitter_access_token:        INST_LTI_TWITTER_ACCESS_TOKEN
  inst_lti_twitter_access_token_secret: INST_LTI_TWITTER_ACCESS_TOKEN_SECRET

development:
  <<: *default

test:
  <<: *default

production:
  blank: intentional
